export {default as CheckOut } from "./CheckOut/CheckOut"
export {default as HomePage } from "./homePage/HomePage"
export {default as SuccessPayment } from "./successPayment/SuccessPayment"
export {default as MyOrders } from "./profile/MyOrders"
export {default as PersonalDetails } from "./profile/PersonalDetails"
export {default as ProfilePage } from "./profile/ProfilePage"
export {default as StoreManager } from "./storeManager/StoreManager"
export {default as Store } from "./storePage/Store"
export {default as StoresListPage } from "./storeslist/StoresListPage"

